"""Add created_at and priority columns (fixed)

Revision ID: d61633dbd384
Revises: 1a6ef6f29d2a
Create Date: 2025-09-04 23:51:54.242140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd61633dbd384'
down_revision = '1a6ef6f29d2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('priority', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('priority')
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
